locadora/config/routes.rb
Rails.application.routes.draw do
  
	root 'films#index'
	resources :films do
		resources :comments
	end
	resources :genres
end

locadora/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

locadora/app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, :rating, :comment, presence:true
  validates_length_of :comment, maximum:200
  RATING=[0,1,2,3,4,5]
  validates_inclusion_of :rating, in: RATING
  belongs_to :film
end

locadora/app/models/film.rb
class Film < ApplicationRecord
  belongs_to :genre
  has_many :comments, dependent: :destroy

  
  def self.created_at
  	where('created_at <= ?', Time.now).order('created_at desc')
  end

  def self.search(search)
  	if search
		where(["name LIKE ?","%#{search}%"]).order('id DESC')
  	else
  		all
  	end
  end

end

locadora/app/models/genre.rb
class Genre < ApplicationRecord

has_many :films, dependent: :destroy
end

locadora/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

locadora/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_film

	def index
		@comments = @film.comments
	end 

	def new
		@comment = @film.comments.new
	end

	def create
		@comment = @film.comments.new(comment_params)
		if @comment.save
			redirect_to film_comments_path(@film), notice:'Comentario gravado com sucesso!'
		else
			render :new
		end
	end 

	private

		def comment_params
			params.require(:comment).permit(:name, :comment, :rating)
		end

		def set_film
			@film = Film.find(params[:film_id])
		end
end

locadora/app/controllers/films_controller.rb
class FilmsController < ApplicationController

	def index
		@films = Film.search(params[:search]).created_at
	end

	def new
		@film = Film.new
	end

	# def create
	# 	@film = Film.new(film_params)
	# 	@film.save
	# 	redirect_to @film
	# end
	def create
		@film = Film.new(film_params)
		if @film.save
			redirect_to @film, notice:"Filme criado com sucesso!"
		else
			render :new
		end
	end

	def show
		@film = Film.find(params[:id])
		@genres = @film.genre
	end

	def edit
		@film = Film.find(params[:id])
	end

	def update
		@film = Film.find(params[:id])
		@film.update(film_params)
		redirect_to @film, notice:"Filme atualizado com sucesso!"
	end

	def destroy
		@film = Film.find(params[:id])
		@film.destroy
		redirect_to films_url, alert:"Filme apagado com sucesso!"
	end

	private
		def film_params
			film_params = params.require(:film).permit(:name, :description, :year, :genre_id, :price, :poster)
		end
	
end

locadora/app/controllers/genres_controller.rb
class GenresController < ApplicationController
	
	def index
		@genres = Genre.all
	end

	def new
		@genre = Genre.new
	end

	def create
		genre_params = params.require(:genre).permit(:name)
		@genre = Genre.new(genre_params)
		@genre.save
		redirect_to @genre
	end
	
	def show
		@genre = Genre.find(params[:id])
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
		genre_params = params.require(:genre).permit(:name)
		@genre.update(genre_params)
		redirect_to @genre 
	end

	def destroy
		@genre = Genre.find(params[:id])
		@genre.destroy
		redirect_to films_url
	end

end

locadora/app/helpers/application_helper.rb
module ApplicationHelper
end

locadora/app/helpers/comments_helper.rb
module CommentsHelper
end

locadora/app/helpers/films_helper.rb
module FilmsHelper

	def imagem(film)
		if film.poster.blank?
			image_tag('no-image.png', width:'200')
		else
			image_tag(film.poster, width: '200')
		end
	end
end

locadora/app/helpers/genres_helper.rb
module GenresHelper
end

locadora/app/views/comments/_form.html.erb
<%= form_for([@film, @comment]) do |f|%>
<%= render 'layouts/errors', object: @comment %>
	<p class="form-group">
	 	<%= f.label :Nome%><br/>
	 	<%= f.text_field :name, autofocus: true, class: "form-control"%>
	 </p>
	 
	 <p class="form-group">
	 	<%= f.label :Estrelas%><br/>
	 	<%= f.select :rating, Comment::RATING, prompt: 'Escolha a quantidade de estrelas', class: "form-control"%>
	 </p>

	 <p class="form-group">
	 	<%= f.label :Comentário%><br/>
	 	<%= f.text_area :comment, placeholder: "Escreva seu comentário...", class: "form-control"%>
	 </p>

	 <p>
	 	<%= f.submit class: 'btn btn-primary'%>
	 	<%= link_to 'Cancelar', root_path, class: 'btn btn-default'%>
	 </p>
<%end%>

locadora/app/views/comments/index.html.erb
<div class="container">
	<%if @film.comments.size > 0%>
		<div class="jumbotron">
			<ul>
				<% @comments.each do |comment|%>
				<li>
					<p>
						<%= comment.name %>
						<small class="small_font_rating"> <%=pluralize(comment.rating, 'estrela', 'estrelas')%></small>
						<small class="small_font"> - <%= time_ago_in_words(comment.created_at)%> atrás</small>
					</p>
					<p>
						<%= comment.comment %>
					</p>
				</li>
				<% end %>
			</ul>
		</div>
	<%else %>
		<div class="jumbotron">
			<h3>Não existem comentários</h3>
		</div>
	<%end%>
	<%= link_to films_path, class: 'btn btn-link' do%>
		<i class="glyphicon glyphicon-home"> Filmes</i>
	<%end%>
		
</div

locadora/app/views/comments/new.html.erb
<div class=container>
	 <div class="panel panel-default">
	 	<div class="panel-heading">
	 		<h2>Novo Comentário</h2>
	 	</div>

	 	<div class="panel-body">
	 		<%= render 'form'%>
	 	</div>
	 </div>
</div>

locadora/app/views/films/_form.html.erb
<%= form_for @film do |f| %>
	<p class="form-group">
		<%= f.label :Nome%><br> 
		<%= f.text_field :name, class: "form-control"%> 
	</p>
	<p class="form-group">
		<%= f.label :Descrição%><br> 
		<%= f.text_area :description, rows:3, class: "form-control"%> 
	</p>
	<p class="form-group">
		<%= f.label :Ano%><br> 
		<%= f.number_field :year, class: "form-control"%>
	</p>
	<p class="form-group">
		<%= f.label :Preço%><br> 
		<%= f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), step: :any, class: "form-control"%>
	</p>
	<p class="form-group">
		<%= f.label :Gênero%><br> 
		<% genre_array = Genre.all.map { |genre| [genre.name, genre.id] } %>
		<%= f.select :genre_id, genre_array, class: "form-control"%>
	</p>

	<p class="form-group">
		<%= f.label :Poster%><br> 
		<%= f.text_field :poster, placeholder: ".GIF, .JPEG ou .PNG", class: "form-control"%> 
	</p>

	<p>
		<%= f.submit class: 'btn btn-primary'%>
		<%= link_to 'Cancelar', root_path, class: 'btn btn-defaut' %>
	</p>

<%end%>

locadora/app/views/films/edit.html.erb
<div class="contaner">
	<div class="panel panel-default">
	  <div class="panel-heading"><h2>Editar Filme</h2></div>
	  <div class="panel-body">
	    <%= render 'form'%>
	  </div>
	</div>
</div>

locadora/app/views/films/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header"><%=pluralize(@films.size, "Filme", "Filmes")%>
				<small class="novo_filme"><%= link_to 'Novo Filme', new_film_path %></small>
			</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			<div class="form-group">
			<%= form_tag(films_path, method: :get) do %>
			  <p><%= text_field_tag :search, params[:search],placeholder: 'Busca por título',class: "form-control"%>
			  </p>
			  <p><button type="submit" class="btn btn-primary form-control">Pesquisar</button>
			  	</p>
			<% end %>
			</div>
		</div>
	</div>
	<hr>

	<% @films.each do |film| %>
		<div class="row">
			<div class="col-md-3">
				<%= link_to imagem(film), film , size:'100'%>
			</div>

			<div class="col-md-7">
				<h3><%= link_to film.name, film %></h3>
				<h4>Descrição</h4>
				<p><%=truncate(film.description, length:100, separator: ' ')%></p>
				<h4>Preço</h4>
				<p><%=number_to_currency(film.price)%></p>
			</div>
		</div>
		<hr>
	<%end%>
</div>

locadora/app/views/films/new.html.erb
<div class="contaner">
	<div class="panel panel-default">
	  <div class="panel-heading"><h2>Novo Filme</h2></div>
	  <div class="panel-body">
	    <%= render 'form'%>
	  </div>
	</div>
</div>
 

locadora/app/views/films/show.html.erb
<div class="container">
	<div class="jumbotron">
		<article>
			<header>
				<h1><%= @film.name %></h1>
				<%= imagem(@film) %>
			</header>
			
			<h2>Descrição</h2>

			<p>
				<%= @film.description %>
			</p>

			<table>
				<tr>
					<th>Ano</th>
					<td><%=@film.year%></td>
				</tr>
				<tr>
					<th>Gênero&nbsp;</th>
					<td><%=@film.genre.name%></td>
				</tr>
				<tr>
					<th>Preço</th>
					<td><%=number_to_currency(@film.price)%></td>
				</tr>
			</table>

		</article>
		<%= link_to pluralize(@film.comments.size, 'Comentário', 'Comentários'), film_comments_path(@film)%>
		<%= link_to 'Novo Comentário', new_film_comment_path(@film), class: 'btn btn-primary'%>
	</div>


	<%= link_to films_path, class: 'btn btn-link' do%>
		<i class="glyphicon glyphicon-home"> Filmes</i>
	<%end%>

	<%= link_to edit_film_path(@film), class: 'btn btn-link' do%>
		<i class="glyphicon glyphicon-edit "> Editar</i>
	<%end%>

	<%= link_to film_path(@film), method: :delete, data:{ confirm: "Deseja deletar este filme?"}, class: 'btn btn-link' do%>
		<i class="glyphicon glyphicon-remove-sign "> Deletar</i>
	<%end%>

</div>

locadora/app/views/genres/_form.html.erb
<%= form_for @genre do |f| %>
	<p>
		<%= f.label :Nome%><br> 
		<%= f.text_field :name%> 
	</p>
	
	<p>
		<%= f.submit class: 'btn btn-primary'%>
		<%= link_to 'Cancelar', genres_path, class: 'btn btn-defaut' %>
	</p>
<%end%>

locadora/app/views/genres/edit.html.erb
<div class="contaner">
	<div class="panel panel-default">
	  <div class="panel-heading"><h2>Editando Gênero</h2></div>
	  <div class="panel-body">
	    <%= render 'form'%>
	  </div>
	</div>
</div>

locadora/app/views/genres/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header"><%=pluralize(@genres.size, "Gênero", "Gêneros")%>
				<small class="novo_filme"><%= link_to 'Novo Gênero', new_genre_path %></small>
			</h1>
		</div>
	</div>

	<ul>
		<% @genres.each do |genre| %>
			<li><%= link_to genre.name, genre %></li>
		<%end%>
	</ul>
</div>

locadora/app/views/genres/new.html.erb
<div class="contaner">
	<div class="panel panel-default">
	  <div class="panel-heading"><h2>Novo Gênero</h2></div>
	  <div class="panel-body">
	    <%= render 'form'%>
	  </div>
	</div>
</div>

locadora/app/views/genres/show.html.erb
<div class="container">
	<div class="jumbotron">

		<article>
				<h2>O nome desse Gênero é:</h2>
			
				<h1><%=@genre.name%></h1>

		</article>
	</div>

	<%= link_to genres_path, class: 'btn btn-link' do%>
		<i class="glyphicon glyphicon-home"> Generos</i>
	<%end%>

	<%= link_to edit_genre_path(@genre), class: 'btn btn-link' do%>
		<i class="glyphicon glyphicon-edit "> Editar</i>
	<%end%>

	<%= link_to genre_path(@genre), method: :delete, data:{ confirm: "Deseja deletar este gênero?"}, class: 'btn btn-link' do%>
		<i class="glyphicon glyphicon-remove-sign "> Deletar</i>
	<%end%>
</div>

locadora/app/views/layouts/_errors.html.erb
<%if object.errors.any? %>
	<div class="alert alert-danger" role="alert">
		<ul>
			<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<%end%>
		</ul>
	</div>
<%end%> 

locadora/app/views/layouts/_flash.html.erb
<%if flash[:notice] %>
  <div class="container">
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:notice]%>
    </div>
  </div>
  <% elsif flash[:alert] %>
   <div class="container">
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:alert]%>
    </div>
  </div>
<%end%>

locadora/app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<p class="text-muted">Ownee Films a sua locadora online</p>
			</div>
			<div class="col-sm-6">
				<p class="text-muted novo_filme">© 2018 - Desenvolvido por Felipe Magalhães</p>
			</div>
		</div>
	</div>

</footer>

locadora/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag('logo_popcorn.png',height:'35', alt:'locadora_online'), root_path, class:'navbar-brand'%>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
           <!--  <li class="active"><%= link_to 'Gêneros', genres_path %><span class="sr-only">(current)</span></li> -->
            <li><%= link_to 'Gêneros', genres_path %></li>
            <li><%= link_to 'Novo Gênero', new_genre_path %></li>
            <li><%= link_to 'Novo Filme', new_film_path %></li>

            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
          <!-- <form class="navbar-form navbar-left">
            <%= form_tag(films_path, method: :get) do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], placeholder: 'Busca por título',class: "form-control"%>
            </div>
            <button type="submit" class="btn btn-default">Pesquisar</button>
            <%end%>
          
          </form> -->

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Filmes', root_path %></li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav> 

locadora/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locadora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1 ">
  </head>

  <body>

    <%= render 'layouts/header'%>
    <%= render 'layouts/flash'%>

    
    <%= yield %>
    
    <%= render 'layouts/footer'%>

  </body>
</html>